# Generated by Django 3.2.4 on 2021-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_rate', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
            options={
                'verbose_name': 'BTC Exchange Rate',
            },
        ),
    ]
